import { MD3LightTheme } from 'react-native-paper';

export const PaperLightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#6CC04A',
    onPrimary: '#FFFFFF',
    primaryContainer: '#E8F5E0',
    onPrimaryContainer: '#1F5120',
    secondary: '#6CC04A',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#E8F5E0',
    onSecondaryContainer: '#1F5120',
    tertiary: '#6CC04A',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#E8F5E0',
    onTertiaryContainer: '#1F5120',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    background: '#F4F5FC',
    onBackground: '#1A1A1A',
    surface: '#FFFFFF',
    onSurface: '#1A1A1A',
    surfaceVariant: '#ECECEC',
    onSurfaceVariant: '#555555',
    outline: '#E1E1E1',
    outlineVariant: '#D3D3D3',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#101010',
    inverseOnSurface: '#F4F5FC',
    inversePrimary: '#6CC04A',
    elevation: {
      level0: 'transparent',
      level1: '#F4F5FC',
      level2: '#ECECEC',
      level3: '#E1E1E1',
      level4: '#D3D3D3',
      level5: '#C8C8C8',
    },
    surfaceDisabled: '#ECECEC',
    onSurfaceDisabled: '#999999',
    backdrop: 'rgba(0, 0, 0, 0.4)',
    // Custom colors for the app
    text: '#1A1A1A',
    textSecondary: '#555555',
    white: '#FFFFFF',
    spacing: 10,
    disabled: 'rgb(180,180,180)',
    card: '#FFFFFF',
    border: '#E1E1E1',
    notification: '#6CC04A',
    cardSurface: '#ECECEC',
    settingsButtonBg: '#ECECEC',
    dropdownBg: '#FFFFFF',
    dropdownText: '#1A1A1A',
    icon: '#1A1A1A',
    subtitle: '#555555',
    buttonText: '#1A1A1A',
    placeholder: '#999999',
    searchBar: '#ECECEC',
    modalBackground: '#FFFFFF',
    headerBackground: '#F4F5FC',
    tabBarBackground: '#FFFFFF',
    tabBarActive: '#6CC04A',
    tabBarInactive: '#999999',
    musicPlayerBg: '#FFFFFF',
    playerControlsBg: '#F4F5FC',
  },
};
